language: cpp

env:
  global:
    - OSRM_TIMEOUT: 60
    - OSRM_PORT: 5000

sudo: false

git:
  depth: 10
  submodules: false

cache:
  directories:
  - mason_packages
  - vendor/bundle

matrix:
  include:
    # Linux + apt packages + extra tools
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=LINUX_DEBIAN CMAKEOPTIONS="-DBUILD_SHARED_LIBS=ON -DBUILD_TOOLS=1" JOBS=2
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','boost-latest/ppa']
          packages: ['g++-4.8','rubygems','protobuf-compiler','libprotoc-dev','libprotobuf7','libprotobuf-dev','libbz2-dev','libstxxl-dev','libstxxl1','libxml2-dev','libzip-dev','lua5.1','liblua5.1-0-dev','libtbb-dev','libboost1.54-all-dev','libgdal-dev']
    # Linux + apt packages + debug build
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=LINUX_DEBIAN TARGET=Debug JOBS=1
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','boost-latest/ppa']
          packages: ['g++-4.8','rubygems','protobuf-compiler','libprotoc-dev','libprotobuf7','libprotobuf-dev','libbz2-dev','libstxxl-dev','libstxxl1','libxml2-dev','libzip-dev','lua5.1','liblua5.1-0-dev','libtbb-dev','libboost1.54-all-dev','libgdal-dev']
    # Linux + mason packages
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=MASON JOBS=2
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8','rubygems']
    # Coverage on OSX (because clang++ on OS X is less likely to be OOM killed)
    - os: osx
      compiler: clang
      env: BUILD_TYPE=MASON COVERAGE=true TARGET=Debug JOBS=4
    # OS X + mason packages
    - os: osx
      compiler: clang
      env: BUILD_TYPE=MASON JOBS=6

before_install:
 - if [[ $(uname -s) == 'Linux' ]]; then
    export CXX="g++-4.8";
    export CC="gcc-4.8";
   fi
 # install deps
 - source ./scripts/${BUILD_TYPE}-install.sh
 # osmosis build
 - if [[ $(uname -s) == 'Darwin' ]]; then brew install osmosis; else curl -s https://gist.githubusercontent.com/DennisOSRM/803a64a9178ec375069f/raw/ | sudo bash; fi

install:
 - source scripts/build.sh
 - make -j${JOBS}
 - make tests -j${JOBS}
 - make benchmarks -j${JOBS}
 - ./datastructure-tests
 - ./algorithm-tests

before_script:
 - cd ..
 - rvm use 1.9.3
 - gem install bundler
 - bundle install --jobs=3

script:
 - cucumber -p verify
 - ./scripts/coverage_report.sh

branches:
  only:
    - master
    - develop
    - masonize

notifications:
 slack: mapbox:PRWTij9HAHnj6pQMDGjqzbfW
 irc:
  channels:
    - irc.oftc.net#osrm
  on_success: change
  on_failure: always
  use_notice: true
  skip_join: false

  recipients:
    - patrick@mapbox.com
  email:
    on_success: change
    on_failure: never       # revert this once it works
