language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    #   - gdb

matrix:
  include:
    # Linux/Debian
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=LINUX_DEBIAN CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release OSRM_PORT=5000
      env: BUILD_TYPE=LINUX_DEBIAN CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Debug OSRM_PORT=5010
      env: BUILD_TYPE=LINUX_DEBIAN CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON OSRM_PORT=5020
    # Coverage
    - os: osx
      compiler: clang
      env: BUILD_TYPE=MASON COVERAGE=true OSRM_PORT=5000
    # Linux
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=MASON OSRM_PORT=5000
    # OS X
    - os: osx
      compiler: clang
      env: BUILD_TYPE=MASON OSRM_PORT=5000

before_install:
- export COVERAGE=${COVERAGE:-false}

install:
 - source ./scripts/${BUILD_TYPE}-install.sh

before_script:
 - rvm use 1.9.3
 - gem install bundler
 - bundle install

 - source scripts/build.sh
script:
 - make -j1
 - make tests
 - make benchmarks
 - ./datastructure-tests
 - ./algorithm-tests
 - cd ..
 - cucumber -p verify
 - if [[ ${COVERAGE} == true ]]; then ./mason_packages/.link/bin/cpp-coveralls --exclude mason_packages --exclude scripts --exclude cmake --exclude osx-10.10 --exclude third_party --exclude test --build-root build --gcov-options '\-lp' --exclude doc --exclude build; fi;
branches:
  only:
    - master
    - develop
    - masonize
env:
  global:
    - JOBS: "1"
    - OSRM_TIMEOUT: "60"
cache:
 - bundler
 # - apt
 - mason_packages
notifications:
 slack: mapbox:PRWTij9HAHnj6pQMDGjqzbfW
 irc:
  channels:
    - irc.oftc.net#osrm
  on_success: change
  on_failure: always
  use_notice: true
  skip_join: false

  recipients:
    - patrick@mapbox.com
  email:
    on_success: change
    on_failure: never       # revert this once it works
