language: cpp
sudo: required
dist: trusty

notifications:
  email: false

matrix:
  include:
    - os: linux
      compiler: gcc

install:
  - bash <(curl -sS https://nixos.org/nix/install)
  - source $HOME/.nix-profile/etc/profile.d/nix.sh

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build

script:
  - nix-shell --pure --run 'cmake ..'
  - nix-shell --pure --run 'cmake --build .'
