language: cpp

env:
  global:
    - OSRM_TIMEOUT: 60
    - OSRM_PORT: 5000

git:
  depth: 10
  submodules: false

cache:
  directories:
  - mason_packages
  - vendor/bundle
  - $HOME/.ccache

# sudo:false not fully viable util:
# https://github.com/travis-ci/travis-ci/issues/3847
# https://github.com/travis-ci/travis-ci/issues/3846
# https://github.com/travis-ci/travis-ci/issues/3759

matrix:
  include:
    # Linux + mason packages
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=MASON JOBS=3
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
    # Linux + apt packages + extra tools
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=LINUX_DEBIAN CMAKEOPTIONS="-DBUILD_SHARED_LIBS=ON -DBUILD_TOOLS=1" JOBS=2
      sudo: required
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','boost-latest']
          packages: ['g++-4.8','protobuf-compiler','libprotobuf-dev','libbz2-dev','libxml2-dev','zlib1g-dev','lua5.1','liblua5.1-0-dev','libgdal1-dev']
    # Linux + apt packages + debug build
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=LINUX_DEBIAN TARGET=Debug JOBS=1
      sudo: required
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test','boost-latest']
          packages: ['g++-4.8','protobuf-compiler','libprotobuf-dev','libbz2-dev','libxml2-dev','zlib1g-dev','lua5.1','liblua5.1-0-dev','libgdal1-dev']
    # Coverage on OSX (because clang++ on OS X is less likely to be OOM killed)
    - os: osx
      compiler: clang
      env: BUILD_TYPE=MASON COVERAGE=true TARGET=Debug JOBS=4
      sudo: false
    # OS X + mason packages
    - os: osx
      compiler: clang
      env: BUILD_TYPE=MASON JOBS=6
      sudo: false

before_install:
 - if [[ $(uname -s) == 'Linux' ]]; then
     if [[ ${BUILD_TYPE} == 'MASON' ]]; then
       echo '#!/bin/bash' > ./cxx_compiler;
       echo 'ccache g++-4.8 "$@"' >> ./cxx_compiler;
       chmod +x ./cxx_compiler;
       export CXX="$(pwd)/cxx_compiler";
       echo '#!/bin/bash' > ./c_compiler;
       echo 'ccache gcc-4.8 "$@"' >> ./c_compiler;
       chmod +x ./c_compiler;
       export CC="$(pwd)/c_compiler";
     else
       export CXX="g++-4.8";
       export CC="gcc-4.8";
       sudo apt-get install -y libtbb-dev libboost1.55-all-dev libstxxl-dev libstxxl1;
     fi
   fi
 # install deps
 - source ./scripts/${BUILD_TYPE}-install.sh
 - source ./scripts/install_osmosis.sh

install:
 - source scripts/build.sh
 - make -j${JOBS}
 - make tests -j${JOBS}
 - make benchmarks -j${JOBS}
 - ./datastructure-tests
 - ./algorithm-tests

before_script:
 - cd ..
 - rvm use 1.9.3
 - gem install bundler
 - bundle install --jobs=3

script:
 - cucumber -p verify
 - ./scripts/coverage_report.sh

branches:
  only:
    - master
    - develop
    - masonize

notifications:
 slack: mapbox:PRWTij9HAHnj6pQMDGjqzbfW
 irc:
  channels:
    - irc.oftc.net#osrm
  on_success: change
  on_failure: always
  use_notice: true
  skip_join: false

  recipients:
    - patrick@mapbox.com
  email:
    on_success: change
    on_failure: never       # revert this once it works
