language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    #   - gdb

matrix:
  include:
    # Linux/Debian
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=LINUX_DEBIAN CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++-4.8" OSRM_PORT=5000 OSRM_TIMEOUT=60
      env: BUILD_TYPE=LINUX_DEBIAN CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-4.8" OSRM_PORT=5010 OSRM_TIMEOUT=60
      env: BUILD_TYPE=LINUX_DEBIAN CMAKEOPTIONS="-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER=g++-4.8" OSRM_PORT=5020 OSRM_TIMEOUT=60
    # Coverage
    - os: osx
      compiler: clang
      env: COVERAGE=true BUILD_TYPE=OSX_COVERAGE MASON=true OSRM_PORT=5000 OSRM_TIMEOUT=60
    # Linux
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=MASON MASON=true OSRM_PORT=5000 OSRM_TIMEOUT=60
    # OS X
    - os: osx
      compiler: clang
      env: BUILD_TYPE=MASON MASON=true OSRM_PORT=5000 OSRM_TIMEOUT=60

before_install:
- export COVERAGE=${COVERAGE:-false}

install:
 - ./scripts/${BUILD_TYPE}-install.sh
 - if [[ $(uname -s) == 'Linux' ]]; then sudo apt-get -q install rubygems; fi;

before_script:
 - rvm use 1.9.3
 - gem install bundler
 - bundle install

 - mkdir build
 - cd build
 - cmake ../ $CMAKEOPTIONS -DBUILD_TOOLS=1
script:
 - make
 - make tests
 - make benchmarks
 - ./datastructure-tests
 - ./algorithm-tests
 - cd ..
 - cucumber -p verify
 - if [[ ${COVERAGE} == true ]]; then ./mason_packages/.link/bin/cpp-coveralls --exclude mason_packages --exclude scripts --exclude cmake --exclude osx-10.10 --exclude third_party --exclude test --build-root build --gcov-options '\-lp' --exclude doc --exclude build; fi;
branches:
  only:
    - master
    - develop
    - masonize
cache:
 - bundler
 - apt
 - mason_packages
notifications:
 slack: mapbox:PRWTij9HAHnj6pQMDGjqzbfW
 irc:
  channels:
    - irc.oftc.net#osrm
  on_success: change
  on_failure: always
  use_notice: true
  skip_join: false

  recipients:
    - patrick@mapbox.com
  email:
    on_success: change
    on_failure: always
